apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chats
  name: chats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chats
  template:
    metadata:
      labels:
        app: chats
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/nestjs-chat-microservice-378423/chats/production
          name: chats
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: PORT
              value: '3004'
            - name: AUTH_HOST
              value: auth-tcp
            - name: AUTH_PORT
              value: '3002'
            - name: PAYMENTS_HOST
              value: payments
            - name: PAYMENTS_PORT
              value: '3001'
          ports:
            - containerPort: 3004
