apiVersion: v1
kind: Service
metadata:
  labels:
    app: chats
  name: chats
spec:
  ports:
    - name: 'http'
      port: 3004
      protocol: TCP
      targetPort: 3004
  selector:
    app: chats
  type: NodePort
